{% set name = "napari-process-points-and-surfaces" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-process-points-and-surfaces-{{ version }}.tar.gz
  sha256: ac0fc58002e9c5a3c8ea11364bf084c1cd7549c02fd62bbdb54d6b8262801da6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - imageio !=2.22.1
    - napari
    - napari-plugin-engine >=0.1.4
    - napari-skimage-regionprops >=0.5.5
    - napari-time-slicer >=0.4.5
    - napari-tools-menu >=0.1.14
    - napari-workflows >=0.2.3
    - numpy
    - pandas
    - python >={{ python_min }},<3.11
    - stackview >=0.5.2
    - vedo >=2022.4.1

test:
  imports:
    - napari_process_points_and_surfaces
  commands:
    - pip list
    # - pip check # Fails on windows due to vtk not being found by the pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/haesleinhuepf/napari-process-points-and-surfaces
  summary: Process and analyze surfaces using open3d and vedo in napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - haesleinhuepf
    - jaimergp
